[workspace]
members = [
    "array-box",
    "geometry-box",
    "string-box",
    "value-box",
    "value-box-ffi"
]
resolver = "2"

[workspace.package]
authors = ["feenk gmbh <contact@feenk.com>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/feenkcom/boxes-rs"
homepage = "https://github.com/feenkcom/boxes-rs"
keywords = ["ffi"]
categories = ["api-bindings"]

[workspace.dependencies]
value-box = { version = "4.0.0", path = "value-box" }
array-box = { version = "4.0.0", path = "array-box" }
geometry-box = { version = "4.0.0", path = "geometry-box" }
string-box = { version = "3.0.0", path = "string-box" }
anyhow = "1.0"
crossbeam = "0.8"
log = "0.4"
paste = "1.0"
thiserror = "2.0"
user-error = "1.2"
widestring = "1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
