[package]
name = "string-box"
version = "4.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Create Rust string from UTF-8 string, byte string or wide string."
readme = "README.md"
documentation = "https://docs.rs/string-box"

[dependencies]
widestring.workspace = true
