[package]
name = "geometry-box"
version = "3.0.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Provides Point, Size and u128 boxes that are safe to pass over ffi."
readme = "README.md"
documentation = "https://docs.rs/geometry-box"

[dependencies]
