[package]
name = "value-box-ffi"
version = "4.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Provides C-like api to family of value-box crates"
readme = "README.md"
documentation = "https://docs.rs/value-box-ffi"

[dependencies]
value-box.workspace = true
array-box = { workspace = true, optional = true }
geometry-box = { workspace = true, optional = true }
string-box = { workspace = true, optional = true }
crossbeam = { workspace = true, optional = true }
paste = { workspace = true, optional = true }

[features]
array-box = [ "dep:array-box", "paste","crossbeam" ]
array-box-string = [ "array-box", "string-box" ]
geometry-box = [ "dep:geometry-box" ]
string-box = [ "dep:string-box" ]
value-box = [ ]
