[package]
name = "value-box-ffi"
version = "1.2.0"
authors = ["feenk gmbh <contact@feenk.com>"]
edition = "2024"
repository = "https://github.com/feenkcom/boxes-rs/tree/main/value-box-ffi"
license = "MIT"
keywords = ["ffi"]
description = "Provides C-like api to family of value-box crates"

[dependencies]
value-box.workspace = true
array-box = { workspace = true, optional = true }
geometry-box = { workspace = true, optional = true }
string-box = { workspace = true, optional = true }
crossbeam = { workspace = true, optional = true }
paste = { workspace = true, optional = true }

[features]
array-box = [ "dep:array-box", "paste","crossbeam" ]
array-box-string = [ "array-box", "string-box" ]
geometry-box = [ "dep:geometry-box" ]
string-box = [ "dep:string-box" ]
value-box = [ ]
