[package]
name = "value-box"
version = "4.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Allows developers to pass Rust-allocated structures over ffi."
readme = "README.md"
documentation = "https://docs.rs/value-box"

[dependencies]
log.workspace = true
thiserror.workspace = true
user-error.workspace = true
anyhow = { workspace = true, optional = true }

[features]
default = [ ]
