[package]
name = "value-box"
version = "2.3.3"
authors = ["feenk gmbh <contact@feenk.com>"]
edition = "2024"
repository = "https://github.com/feenkcom/boxes-rs/tree/main/value-box"
license = "MIT"
keywords = ["ffi"]
description = "Allows developers to pass Rust-allocated structures over ffi."

[dependencies]
log.workspace = true
thiserror.workspace = true
user-error.workspace = true
anyhow = { workspace = true, optional = true }

[features]
default = [ ]
